import {
  Pressable,
  ScrollView,
  StyleSheet,
  Text,
  View,
} from "react-native";

import { router } from "expo-router";
import { useEffect, useMemo, useState } from "react";

import { theme } from "../constants/theme";
import { useAuth } from "../context/AuthContext";

import { getAthleteData } from "../lib/athlete";
import { buildAthleteModel } from "../lib/physiology/athleteModel";

import { AthleteData } from "../types/athlete";

export default function PowerPage() {
  const { user } = useAuth();

  const [athlete, setAthlete] =
    useState<AthleteData | null>(null);

  const [isLoading, setIsLoading] =
    useState(true);

  const [error, setError] =
    useState<string | null>(null);

  useEffect(() => {
    if (!user) {
      setAthlete(null);
      setIsLoading(false);
      return;
    }

    let isMounted = true;

    async function loadPowerData() {
      try {
        setIsLoading(true);
        setError(null);

        const athleteData =
          await getAthleteData(user!.id);

        if (isMounted) {
          setAthlete(athleteData);
        }
      } catch (loadError) {
        console.error(
          "Failed to load power data:",
          loadError
        );

        if (isMounted) {
          setError(
            "Unable to load your power model."
          );
        }
      } finally {
        if (isMounted) {
          setIsLoading(false);
        }
      }
    }

    loadPowerData();

    return () => {
      isMounted = false;
    };
  }, [user]);

  const model = useMemo(() => {
    if (!athlete) {
      return null;
    }

    return buildAthleteModel(athlete);
  }, [athlete]);

  const profile = athlete?.profile;
  const powerProfile = athlete?.powerProfile;

  const firstName =
    profile?.first_name ?? "";

  const firstInitial =
    firstName.charAt(0).toUpperCase() || "A";

  /*
   * The power curve generated by athleteModel contains
   * the modeled values derived from CP + W′.
   */
  const curve = model?.powerCurve ?? [];

  /*
   * Scale bars relative to the highest modeled power
   * currently displayed.
   */
  const maxCurvePower =
    curve.length > 0
      ? Math.max(
          ...curve.map(
            (point) => point.powerWatts
          )
        )
      : 0;

  const lastUpdated =
    formatRecordedDate(
      model?.recordedAt ?? null
    );

  return (
    <View style={styles.page}>
      <ScrollView
        showsVerticalScrollIndicator={false}
        contentContainerStyle={
          styles.scrollContent
        }
      >
        <View style={styles.container}>
          {/* Header */}
          <View style={styles.header}>
            <Pressable
              onPress={() =>
                router.push("/")
              }
            >
              <Text style={styles.logo}>
                VECTOR
              </Text>
            </Pressable>

            <View style={styles.avatar}>
              <Text style={styles.avatarText}>
                {firstInitial}
              </Text>
            </View>
          </View>

          {/* Hero */}
          <View style={styles.hero}>
            <Text style={styles.eyebrow}>
              POWER PROFILE
            </Text>

            <Text style={styles.title}>
              Your performance model.
            </Text>

            <Text style={styles.subtitle}>
              A living model of your aerobic and
              anaerobic capabilities.
            </Text>
          </View>

          {error ? (
            <View style={styles.errorCard}>
              <Text style={styles.errorText}>
                {error}
              </Text>
            </View>
          ) : null}

          {/* Main metrics */}
          <View style={styles.metrics}>
            <Metric
              label="Critical Power"
              value={
                isLoading
                  ? "..."
                  : model
                    ? `${Math.round(model.cpWatts)} W`
                    : "—"
              }
              secondary={
                model
                  ? `${(
                      model.cpWatts /
                      model.inputs.weightKg
                    ).toFixed(2)} W/kg`
                  : undefined
              }
            />

            <Metric
              label="W′"
              value={
                isLoading
                  ? "..."
                  : model
                    ? `${model.wPrimeKj.toFixed(
                        1
                      )} kJ`
                    : "—"
              }
            />

            <Metric
              label="Est. VO₂max"
              value={
                isLoading
                  ? "..."
                  : model
                    ? model.vo2Max.toFixed(1)
                    : "—"
              }
            />
          </View>

          {/* Power curve */}
          <View style={styles.sectionHeader}>
            <View>
              <Text
                style={
                  styles.sectionEyebrow
                }
              >
                POWER-DURATION MODEL
              </Text>

              <Text
                style={styles.sectionTitle}
              >
                Current capabilities
              </Text>
            </View>

            <Text style={styles.period}>
              Current model
            </Text>
          </View>

          <View style={styles.chartCard}>
            {isLoading ? (
              <View
                style={
                  styles.chartMessage
                }
              >
                <Text
                  style={
                    styles.chartMessageText
                  }
                >
                  Loading power model...
                </Text>
              </View>
            ) : model && curve.length > 0 ? (
              <View style={styles.chart}>
                {curve.map((item) => {
                  const barHeight =
                    maxCurvePower > 0
                      ? Math.max(
                          20,
                          (item.powerWatts /
                            maxCurvePower) *
                            165
                        )
                      : 20;

                  return (
                    <View
                      key={
                        item.durationSeconds
                      }
                      style={
                        styles.chartColumn
                      }
                    >
                      <Text
                        style={
                          styles.powerValue
                        }
                      >
                        {Math.round(
                          item.powerWatts
                        )}
                      </Text>

                      <View
                        style={[
                          styles.bar,
                          {
                            height:
                              barHeight,
                          },
                        ]}
                      />

                      <Text
                        style={
                          styles.duration
                        }
                      >
                        {shortenDurationLabel(
                          item.label
                        )}
                      </Text>
                    </View>
                  );
                })}
              </View>
            ) : (
              <View
                style={
                  styles.chartMessage
                }
              >
                <Text
                  style={
                    styles.chartMessageTitle
                  }
                >
                  Not enough power data
                </Text>

                <Text
                  style={
                    styles.chartMessageText
                  }
                >
                  Add valid 1, 5 and
                  12-minute maximal efforts
                  to generate your model.
                </Text>
              </View>
            )}

            <View style={styles.chartFooter}>
              <View>
                <Text
                  style={
                    styles.chartFooterLabel
                  }
                >
                  MODEL
                </Text>

                <Text
                  style={
                    styles.chartFooterValue
                  }
                >
                  Morton 3-parameter
                </Text>
              </View>

              <View>
                <Text
                  style={
                    styles.chartFooterLabel
                  }
                >
                  LAST UPDATED
                </Text>

                <Text
                  style={
                    styles.chartFooterValue
                  }
                >
                  {isLoading
                    ? "..."
                    : lastUpdated}
                </Text>
              </View>
            </View>
          </View>

          {/* Model information */}
          <View style={styles.lowerGrid}>
            <View style={styles.confidenceCard}>
              <Text style={styles.cardEyebrow}>
                MODEL PARAMETERS
              </Text>

              <View style={styles.modelParameterMain}>
                <Text style={styles.parameterNumber}>
                  {isLoading
                    ? "..."
                    : model
                      ? `${Math.round(model.pMaxWatts)} W`
                      : "—"}
                </Text>

                <Text style={styles.parameterMainLabel}>
                  Estimated Pmax
                </Text>
              </View>

              <View style={styles.parameterDivider} />

              <View style={styles.parameterRow}>
                <Text style={styles.parameterLabel}>
                  Critical Power
                </Text>

                <Text style={styles.parameterValue}>
                  {model
                    ? `${Math.round(model.cpWatts)} W`
                    : "—"}
                </Text>
              </View>

              <View style={styles.parameterRow}>
                <Text style={styles.parameterLabel}>
                  W′
                </Text>

                <Text style={styles.parameterValue}>
                  {model
                    ? `${model.wPrimeKj.toFixed(1)} kJ`
                    : "—"}
                </Text>
              </View>

              <Text style={styles.cardDescription}>
                Pmax, Critical Power and W′ are the three
                parameters of your current Morton power-duration
                model.
              </Text>
            </View>

            <View style={styles.testCard}>
              <Text
                style={styles.cardEyebrow}
              >
                CURRENT INPUTS
              </Text>

              <PowerInputRow
                label="1 minute"
                value={
                  powerProfile?.one_minute_watts !=
                  null
                    ? `${powerProfile.one_minute_watts} W`
                    : "—"
                }
              />

              <PowerInputRow
                label="5 minutes"
                value={
                  powerProfile?.five_minute_watts !=
                  null
                    ? `${powerProfile.five_minute_watts} W`
                    : "—"
                }
              />

              <PowerInputRow
                label="12 minutes"
                value={
                  powerProfile?.twelve_minute_watts !=
                  null
                    ? `${powerProfile.twelve_minute_watts} W`
                    : "—"
                }
                last
              />

              <Pressable
                style={styles.editPowerButton}
                onPress={() =>
                  router.push("/profile")
                }
              >
                <Text
                  style={
                    styles.editPowerButtonText
                  }
                >
                  Edit power data
                </Text>

                <Text
                  style={
                    styles.testArrow
                  }
                >
                  →
                </Text>
              </Pressable>
            </View>
          </View>

          {/* Insight */}
          <View style={styles.insightCard}>
            <Text
              style={styles.insightEyebrow}
            >
              VECTOR MODEL
            </Text>

            <Text
              style={styles.insightTitle}
            >
              {model
                ? "Your current physiology model is ready."
                : "More power data are required."}
            </Text>

            <Text
              style={
                styles.insightDescription
              }
            >
              {model
                ? `Your current model estimates a Critical Power of ${Math.round(
                    model.cpWatts
                  )} W with ${model.wPrimeKj.toFixed(
                    1
                  )} kJ of W′. These values are derived from your recorded 1, 5 and 12-minute maximal efforts.`
                : "Once valid maximal efforts are available, Vector can calculate your Critical Power, W′ capacity and modeled power-duration relationship."}
            </Text>
          </View>
        </View>
      </ScrollView>

      <BottomNav />
    </View>
  );
}

type MetricProps = {
  label: string;
  value: string;
  secondary?: string;
};

function Metric({
  label,
  value,
  secondary,
}: MetricProps) {
  return (
    <View style={styles.metric}>
      <Text style={styles.metricLabel}>
        {label}
      </Text>

      <Text style={styles.metricValue}>
        {value}
      </Text>

      {secondary ? (
        <Text style={styles.metricSecondary}>
          {secondary}
        </Text>
      ) : null}

      <Text style={styles.metricContext}>
        Current estimate
      </Text>
    </View>
  );
}

type PowerInputRowProps = {
  label: string;
  value: string;
  last?: boolean;
};

function PowerInputRow({
  label,
  value,
  last,
}: PowerInputRowProps) {
  return (
    <View
      style={[
        styles.powerInputRow,
        last
          ? styles.powerInputRowLast
          : undefined,
      ]}
    >
      <Text style={styles.powerInputLabel}>
        {label}
      </Text>

      <Text style={styles.powerInputValue}>
        {value}
      </Text>
    </View>
  );
}

function shortenDurationLabel(
  label: string
) {
  return label
    .replace(" min", "m")
    .replace(" hr", "h")
    .replace(" sec", "s");
}

function formatRecordedDate(
  recordedAt: string | null
) {
  if (!recordedAt) {
    return "—";
  }

  const date = new Date(recordedAt);

  if (Number.isNaN(date.getTime())) {
    return "—";
  }

  return date.toLocaleDateString(
    undefined,
    {
      month: "short",
      day: "numeric",
    }
  );
}

function BottomNav() {
  return (
    <View style={styles.navWrapper}>
      <View style={styles.nav}>
        <Nav
          symbol="⌂"
          label="Home"
          onPress={() =>
            router.push("/dashboard")
          }
        />

        <Nav
          symbol="⌁"
          label="Training"
          onPress={() =>
            router.push("/training")
          }
        />

        <Nav
          symbol="↗"
          label="Power"
          active
          onPress={() =>
            router.push("/power")
          }
        />

        <Nav
          symbol="○"
          label="Profile"
          onPress={() =>
            router.push("/profile")
          }
        />
      </View>
    </View>
  );
}

type NavProps = {
  symbol: string;
  label: string;
  active?: boolean;
  onPress: () => void;
};

function Nav({
  symbol,
  label,
  active,
  onPress,
}: NavProps) {
  return (
    <Pressable
      style={[
        styles.navItem,
        active
          ? styles.navItemActive
          : undefined,
      ]}
      onPress={onPress}
    >
      <Text
        style={[
          styles.navSymbol,
          active
            ? styles.navSymbolActive
            : undefined,
        ]}
      >
        {symbol}
      </Text>

      <Text
        style={[
          styles.navLabel,
          active
            ? styles.navLabelActive
            : undefined,
        ]}
      >
        {label}
      </Text>
    </Pressable>
  );
}

const styles = StyleSheet.create({
  page: {
    flex: 1,
    backgroundColor:
      theme.colors.background,
  },

  scrollContent: {
    paddingBottom: 140,
  },

  container: {
    width: "100%",
    maxWidth: 1050,
    alignSelf: "center",
    paddingHorizontal: 24,
  },

  header: {
    height: 90,
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },

  logo: {
    color: theme.colors.text,
    fontSize: 18,
    fontWeight: "800",
    letterSpacing: 4,
  },

  avatar: {
    width: 38,
    height: 38,
    borderRadius: 19,
    backgroundColor:
      theme.colors.surface,
    borderWidth: 1,
    borderColor: theme.colors.border,
    alignItems: "center",
    justifyContent: "center",
  },

  avatarText: {
    color: theme.colors.text,
    fontWeight: "700",
  },

  hero: {
    paddingTop: 42,
    paddingBottom: 45,
  },

  eyebrow: {
    color: theme.colors.accent,
    fontSize: 10,
    fontWeight: "700",
    letterSpacing: 1.5,
  },

  title: {
    color: theme.colors.text,
    fontSize: 40,
    fontWeight: "700",
    letterSpacing: -1.5,
    marginTop: 10,
  },

  subtitle: {
    color:
      theme.colors.textSecondary,
    fontSize: 16,
    marginTop: 10,
  },

  modelParameterMain: {
    marginTop: 12,
  },

  parameterNumber: {
    color: theme.colors.text,
    fontSize: 32,
    fontWeight: "700",
  },

  parameterMainLabel: {
    color: theme.colors.textSecondary,
    fontSize: 10,
    marginTop: 3,
  },

  parameterDivider: {
    height: 1,
    backgroundColor: theme.colors.border,
    marginVertical: 16,
  },

  parameterRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 8,
  },

  parameterLabel: {
    color: theme.colors.textSecondary,
    fontSize: 11,
  },

  parameterValue: {
    color: theme.colors.text,
    fontSize: 11,
    fontWeight: "600",
  },

  errorCard: {
    backgroundColor: "#FDECEC",
    borderRadius: theme.radius.md,
    padding: 14,
    marginBottom: 20,
  },

  errorText: {
    color: "#A64E4E",
    fontSize: 12,
  },

  metrics: {
    flexDirection: "row",
    gap: 12,
    flexWrap: "wrap",
  },

  metric: {
    flex: 1,
    minWidth: 210,
    padding: 22,
    borderRadius: 18,
    backgroundColor:
      theme.colors.surface,
    borderWidth: 1,
    borderColor: theme.colors.border,
  },

  metricLabel: {
    color:
      theme.colors.textSecondary,
    fontSize: 11,
  },

  metricValue: {
    color: theme.colors.text,
    fontSize: 32,
    fontWeight: "700",
    marginTop: 7,
  },

  metricContext: {
    color: theme.colors.accent,
    fontSize: 11,
    fontWeight: "600",
    marginTop: 6,
  },

  sectionHeader: {
    marginTop: 55,
    marginBottom: 16,
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "flex-end",
  },

  sectionEyebrow: {
    color:
      theme.colors.textSecondary,
    fontSize: 9,
    fontWeight: "700",
    letterSpacing: 1.2,
  },

  sectionTitle: {
    color: theme.colors.text,
    fontSize: 24,
    fontWeight: "600",
    marginTop: 5,
  },

  period: {
    color:
      theme.colors.textSecondary,
    fontSize: 11,
  },

  chartCard: {
    padding: 26,
    borderRadius: 20,
    backgroundColor:
      theme.colors.surface,
    borderWidth: 1,
    borderColor: theme.colors.border,
  },

  chart: {
    height: 230,
    flexDirection: "row",
    alignItems: "flex-end",
    justifyContent: "space-between",
  },

  chartColumn: {
    flex: 1,
    alignItems: "center",
  },

  powerValue: {
    color:
      theme.colors.textSecondary,
    fontSize: 9,
    marginBottom: 6,
  },

  bar: {
    width: "48%",
    maxWidth: 34,
    minWidth: 10,
    borderRadius: 5,
    backgroundColor:
      theme.colors.accent,
  },

  duration: {
    color:
      theme.colors.textSecondary,
    fontSize: 9,
    marginTop: 8,
  },

  chartMessage: {
    height: 230,
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 30,
  },

  chartMessageTitle: {
    color: theme.colors.text,
    fontSize: 16,
    fontWeight: "600",
  },

  chartMessageText: {
    color:
      theme.colors.textSecondary,
    fontSize: 12,
    lineHeight: 19,
    textAlign: "center",
    marginTop: 6,
  },

  chartFooter: {
    flexDirection: "row",
    gap: 45,
    marginTop: 26,
    paddingTop: 20,
    borderTopWidth: 1,
    borderTopColor:
      theme.colors.border,
  },

  chartFooterLabel: {
    color:
      theme.colors.textSecondary,
    fontSize: 8,
    letterSpacing: 1,
  },

  chartFooterValue: {
    color: theme.colors.text,
    fontSize: 12,
    fontWeight: "600",
    marginTop: 4,
  },

  lowerGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 12,
    marginTop: 12,
  },

  confidenceCard: {
    flex: 1,
    minWidth: 300,
    padding: 24,
    borderRadius: 18,
    backgroundColor:
      theme.colors.surface,
    borderWidth: 1,
    borderColor: theme.colors.border,
  },

  testCard: {
    flex: 1,
    minWidth: 300,
    padding: 24,
    borderRadius: 18,
    backgroundColor:
      theme.colors.accentSoft,
  },

  cardEyebrow: {
    color:
      theme.colors.textSecondary,
    fontSize: 9,
    fontWeight: "700",
    letterSpacing: 1.2,
  },

  confidenceRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    marginTop: 10,
  },

  confidenceNumber: {
    color: theme.colors.text,
    fontSize: 32,
    fontWeight: "700",
  },

  confidencePill: {
    backgroundColor:
      theme.colors.accentSoft,
    borderRadius: 999,
    paddingHorizontal: 9,
    paddingVertical: 5,
  },

  confidencePillText: {
    color: theme.colors.accent,
    fontSize: 9,
    fontWeight: "700",
  },

  progressBackground: {
    height: 5,
    backgroundColor:
      theme.colors.border,
    borderRadius: 999,
    marginTop: 18,
    overflow: "hidden",
  },

  progressFill: {
    height: "100%",
    backgroundColor:
      theme.colors.accent,
    borderRadius: 999,
  },

  cardDescription: {
    color:
      theme.colors.textSecondary,
    fontSize: 12,
    lineHeight: 19,
    marginTop: 16,
  },

  powerInputRow: {
    minHeight: 43,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    borderBottomWidth: 1,
    borderBottomColor:
      theme.colors.border,
  },

  powerInputRowLast: {
    borderBottomWidth: 0,
  },

  powerInputLabel: {
    color:
      theme.colors.textSecondary,
    fontSize: 11,
  },

  powerInputValue: {
    color: theme.colors.text,
    fontSize: 12,
    fontWeight: "600",
  },

  editPowerButton: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginTop: 18,
  },

  editPowerButtonText: {
    color: theme.colors.accent,
    fontSize: 11,
    fontWeight: "700",
  },

  testArrow: {
    color: theme.colors.accent,
    fontSize: 20,
  },

  insightCard: {
    marginTop: 12,
    padding: 26,
    borderRadius: 20,
    backgroundColor:
      theme.colors.text,
  },

  insightEyebrow: {
    color: theme.colors.accent,
    fontSize: 9,
    fontWeight: "700",
    letterSpacing: 1.2,
  },

  insightTitle: {
    color: theme.colors.white,
    fontSize: 23,
    fontWeight: "600",
    marginTop: 8,
  },

  insightDescription: {
    color: "#B8C0BD",
    fontSize: 13,
    lineHeight: 21,
    marginTop: 10,
    maxWidth: 720,
  },

  navWrapper: {
    position: "absolute",
    left: 0,
    right: 0,
    bottom: 22,
    alignItems: "center",
    paddingHorizontal: 18,
  },

  nav: {
    width: "100%",
    maxWidth: 520,
    minHeight: 68,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-around",
    padding: 7,
    borderRadius: 24,
    backgroundColor: "#FFFFFFF2",
    borderWidth: 1,
    borderColor: theme.colors.border,
    shadowColor: "#000000",
    shadowOffset: {
      width: 0,
      height: 8,
    },
    shadowOpacity: 0.08,
    shadowRadius: 24,
    elevation: 8,
  },

  navItem: {
    minWidth: 80,
    minHeight: 52,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 18,
  },

  navItemActive: {
    backgroundColor:
      theme.colors.accentSoft,
  },

  navSymbol: {
    color:
      theme.colors.textSecondary,
    fontSize: 18,
  },

  navSymbolActive: {
    color: theme.colors.accent,
  },

  navLabel: {
    color:
      theme.colors.textSecondary,
    fontSize: 10,
    marginTop: 3,
  },

  navLabelActive: {
    color: theme.colors.text,
    fontWeight: "600",
  },

  metricSecondary: {
    color: theme.colors.textSecondary,
    fontSize: 12,
    fontWeight: "500",
    marginTop: 2,
  },
});